### ISSUE TITLE
Does not work with Edge 

### ISSUE THREAD

**Issue by juriz889** [SAP/ui5-webcomponents-sample-react#8] opened 2019-04-17 08:05 UTC
HI,

on my Windows 10 machine the sample app does not work with Microsoft Edge. It seems that none CSS are applied as the page does only contain texts.

![WebComponentsEdge](https://user-images.githubusercontent.com/19668532/56271238-49556580-60f8-11e9-82a2-55ff6994d54e.JPG)

There are no errors in the log. 

BR,
Juri

**Comment by MapTo0** [comment] 2019-04-17 13:36
Duplicate of https://github.com/SAP/ui5-webcomponents-sample-react/issues/4

**Comment by MapTo0** [comment] 2019-04-17 13:39
Hey @juriz889 

We already have an issue for adding that support.
Until we get it done in the applications, you can read out answer in:

https://github.com/SAP/ui5-webcomponents/issues/160

It should be working fine for React app as well.

**Closed by MapTo0** 2019-04-17 13:39 UTC
